# Generated by Django 3.1.5 on 2021-01-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20210114_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
